POST  http://localhost:9000/loginuser
content-type: application/json

{
    "password":"dupa1234",
    "email":"dupa@wp.pl"
}

###

POST  http://localhost:9000/loginuser
content-type: application/json

{
    "password":"dupa1234",
    "email":"sl.tuszko@gmail.com"
}

###

GET  http://localhost:9000/authtoken
Auth: Bearer eyJhbGciOiJIUzI1NiJ9.c2wudHVzemtvQGdtYWlsLmNvbQ.AtxvfoBCcKj_dKb1LMllt9F_MplWfXQuWS-OhGQ5OIk

###

GET  http://localhost:9000/persistence
###
POST  http://localhost:9000/register
content-type: application/json

{
    "name":"dupa",
    "email":"dupaa@duuoupa.pl",
    "password":"dupa"
}

###
POST  http://localhost:9000/login
content-type: application/json

{
    "email":"dupa@dupa",
    "password":"dupa"
}

###

POST  http://socialback.bieda.it/login
content-type: application/json

{
    "email":"dupa@dupa",
    "password":"dupam"
}
###

POST  http://localhost:9000/jwt
content-type: application/json

{
   "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZHVwYSIsInBhc3N3b3JkIjoiJDJiJDEwJGtrSWJZdWNVRncxdWh4YkswWXdTS2V3b0JESlF5NU41ODJYc3FNbGZKMWJ3dG1mRjFnZ29tIiwiaWF0IjoxNjc0MDU3MzA1fQ.GutAVgxeKwtJMi_yx4kJ3sXqm76Q9dDH37hTrO9h5Ig"
}
###
POST  http://localhost:9000/pro
content-type: application/json

{
   "token": "eyJhbGciOiJIUzI1NiJ9.ZHVwYUBkdXBh.-37Xdmi5gfXD2LHpilAGqWUSG-53wccLkRFZPsqzuCQ"
}
